name: Say hello

on: 
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello, world!"
      - name: Show me the date
        run: date
      - name: Rest
        run: ls -l 
