name: Deployment Pipeline

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test  
        run: npm test

      - name: Deploy to Vercel
        uses: withvercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Necesitas configurar este secret
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} 

      - name: Notify deployment success
        run: echo "Deployment to production successful!"
      - name: Notify deployment failure 
        if: failure()
        run: echo "Deployment to production failed!"'
